import { expect, test } from "@playwright/test";

test("3. 줄 선택과 해제를 탭별로 저장하고 새로고침 후 복원한다", async ({ page }) => {
  await page.goto("http://localhost:3000");
  const editor = page.locator("textarea");
  const lines = page.locator('.line-rail [role="button"]');
  await editor.fill("one\ntwo\nthree");
  await lines.nth(1).click();
  await lines.nth(2).click();
  await page.getByRole("button", { name: "새 탭 추가" }).click();
  await editor.fill("other\nnote");
  await expect(lines.first()).toHaveAttribute("aria-pressed", "false");
  await lines.first().click();
  await page.locator('[role="tab"]').first().click();
  await expect(lines.first()).toHaveAttribute("aria-pressed", "false");
  await expect(lines.nth(1)).toHaveAttribute("aria-pressed", "true");
  await expect(lines.nth(2)).toHaveAttribute("aria-pressed", "true");
  await page.reload();
  await expect(lines.nth(1)).toHaveAttribute("aria-pressed", "true");
  await expect(lines.nth(2)).toHaveAttribute("aria-pressed", "true");
  await lines.nth(1).click();
  await page.reload();
  await expect(lines.nth(1)).toHaveAttribute("aria-pressed", "false");
  await expect(lines.nth(2)).toHaveAttribute("aria-pressed", "true");
  await page.locator('[role="tab"]').nth(1).click();
  await expect(lines.first()).toHaveAttribute("aria-pressed", "true");
  await expect(lines.nth(1)).toHaveAttribute("aria-pressed", "false");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload();
  await expect(lines.first()).toHaveAttribute("aria-pressed", "true");
  await expect(lines.nth(1)).toHaveAttribute("aria-pressed", "false");
});